Handle errors in mkioctls.c

diff --git a/lib/libsysdecode/mkioctls b/lib/libsysdecode/mkioctls
--- a/lib/libsysdecode/mkioctls
+++ b/lib/libsysdecode/mkioctls
@@ -3,11 +3,6 @@
 # $FreeBSD$
 
 set -e
-# if /bin/sh is bash this will avoid further errors due to missing commands
-if set -o | grep pipefail > /dev/null; then
-	set -o pipefail
-fi
-
 if [ $# -ne 1 ]; then
 	echo "usage: sh $0 include-dir"
 	exit 1
@@ -21,6 +16,11 @@ LC_ALL=C; export LC_ALL
 # XXX should we use an ANSI cpp?
 ioctl_includes=$(
 	cd $includedir
+	set -e
+	# if /bin/sh is bash this will avoid further errors due to missing commands
+	if set -o | grep pipefail > /dev/null; then
+		set -o pipefail
+	fi
 
 	filter='tee'
 	if [ "${MK_PF}" = "no" ]; then
@@ -33,6 +33,11 @@ ioctl_includes=$(
 '^#[ 	]*define[ 	]+[A-Za-z_][A-Za-z0-9_]*[ 	]+_IO[^a-z0-9_]' |
 		awk '{printf("#include <%s>\\n", $1)}'
 )
+
+if [ -z "$ioctl_includes" ]; then
+	echo "Failed to build list of ioctl headers"
+	exit 1
+fi
 
 awk -v x="$ioctl_includes" 'BEGIN {print x}' |
 	$CPP -nostdinc -I$includedir -dM -DCOMPAT_43TTY - |
